[package]
name = "get-aoc-input"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
nom = "7.1.3"
reqwest = { version = "0.11.22", features = ["blocking"] }
dotenv = "0.15"  # si quieres cargar variables de entorno desde .env
